@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Mar 08 20:06:17 -0700 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim cpu_top_level_testbench_behav -key {Behavioral:sim_1:Functional:cpu_top_level_testbench} -tclbatch cpu_top_level_testbench.tcl -view C:/Users/Kheph/Documents/Projects/School/ECE449CPU/ECE449_LAB_CPU/project_1/cpu_top_level_testbench_behav.wcfg -log simulate.log"
call xsim  cpu_top_level_testbench_behav -key {Behavioral:sim_1:Functional:cpu_top_level_testbench} -tclbatch cpu_top_level_testbench.tcl -view C:/Users/Kheph/Documents/Projects/School/ECE449CPU/ECE449_LAB_CPU/project_1/cpu_top_level_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
