# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Kheph/Documents/Projects/School/ECE449CPU/ECE449_LAB_CPU/BASYS3_Master.xdc

# IP: ip/CPU_ROM/CPU_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_ROM || ORIG_REF_NAME==CPU_ROM} -quiet] -quiet
